### ISSUE TITLE
The template for FW creates a bucket

### ISSUE THREAD

**Issue by mathieubellon** [SEKOIA-IO/sekoiaio-cti-aws-integration#5]
Either we choose to create it on behalf of the user or not

**Comment by maxime-el-haddari** [comment]
Currently on both stack, we require the user to provide a bucket. It is used to store the `zip` file of `LambdaFunction`.
In the case it stores the indicators as a file which is read by `GuardDuty`.
It is also better since a bucket name is unique per region which is why we let the user provide its own bucket.
